import type { EngineerAllocation, ProgrammeNode } from "@/components/programme/types";

import { rollupTotalHoursInTree } from "./totalHoursRollup";

type SeedAlloc = { code: string; isLead: boolean; plannedHrs: null; forecastHrs: null };

const e = (code: string, isLead = false): SeedAlloc => ({
  code,
  isLead,
  plannedHrs: null,
  forecastHrs: null,
});

export type SeedProgrammeNode = Omit<ProgrammeNode, "children" | "engineers"> & {
  children: SeedProgrammeNode[];
  engineers?: SeedAlloc[];
};

/**
 * Static WBS for the sample project (`SEED_PROJECT_ID` in `seedConfig.ts`).
 * Engineer rows use codes; `buildProgrammeNodesFromSeed` maps codes to `engineer_pool.id`.
 * Used only by `npm run seed` — the app loads the tree from Supabase.
 */
export const seedProgrammeData: SeedProgrammeNode[] = [
  {
    id: "s11",
    name: "11. CGMM - Early Design Workstream",
    type: "scope",
    totalHours: 79,
    start: "25-Nov-25",
    finish: "13-Mar-26",
    forecastTotalHours: 79,
    status: "",
    engineers: [],
    children: [
      {
        id: "t11-1",
        name: "CGMM",
        type: "task",
        totalHours: 76,
        start: "25-Nov-25",
        finish: "10-Mar-26",
        forecastTotalHours: 76,
        status: "",
        children: [
          {
            id: "a3630",
            activityId: "A3630",
            name: "NR options/HS2 station development - get list",
            type: "activity",
            totalHours: 3,
            start: "25-Nov-25",
            finish: "27-Nov-25",
            forecastTotalHours: 3,
            status: "In Progress",
            children: [],
          },
          {
            id: "a3640",
            activityId: "A3640",
            name: "CGMM Development",
            type: "activity",
            totalHours: 10,
            start: "30-Dec-25",
            finish: "12-Jan-26",
            forecastTotalHours: 10,
            status: "In Progress",
            children: [],
          },
          {
            id: "a3650",
            activityId: "A3650",
            name: "Draft Report",
            type: "activity",
            totalHours: 10,
            start: "13-Jan-26",
            finish: "02-Feb-26",
            forecastTotalHours: 10,
            status: "In Progress",
            children: [],
          },
          {
            id: "a3660",
            activityId: "A3660",
            name: "Internal review",
            type: "activity",
            totalHours: 5,
            start: "03-Feb-26",
            finish: "09-Feb-26",
            forecastTotalHours: 5,
            status: "In Progress",
            children: [],
          },
          {
            id: "a3670",
            activityId: "A3670",
            name: "Issue draft to CP",
            type: "activity",
            totalHours: 2,
            start: "10-Feb-26",
            finish: "11-Feb-26",
            forecastTotalHours: 2,
            status: "In Progress",
            children: [],
          },
          {
            id: "a3680",
            activityId: "A3680",
            name: "CP Review",
            type: "activity",
            totalHours: 10,
            start: "12-Feb-26",
            finish: "25-Feb-26",
            forecastTotalHours: 10,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3690",
            activityId: "A3690",
            name: "Presentation to NR",
            type: "activity",
            totalHours: 2,
            start: "26-Feb-26",
            finish: "27-Feb-26",
            forecastTotalHours: 2,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3700",
            activityId: "A3700",
            name: "Update comments from NR and CP",
            type: "activity",
            totalHours: 5,
            start: "02-Mar-26",
            finish: "06-Mar-26",
            forecastTotalHours: 5,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3710",
            activityId: "A3710",
            name: "Final Issue",
            type: "activity",
            totalHours: 2,
            start: "09-Mar-26",
            finish: "10-Mar-26",
            forecastTotalHours: 2,
            status: "Not Started",
            children: [],
          },
        ],
      },
      {
        id: "t11-2",
        name: "Mitigation",
        type: "task",
        totalHours: 45,
        start: "12-Jan-26",
        finish: "13-Mar-26",
        forecastTotalHours: 45,
        status: "",
        children: [
          {
            id: "a3720",
            activityId: "A3720",
            name: "Mitigation requirements critical assets",
            type: "activity",
            totalHours: 7,
            start: "12-Jan-26",
            finish: "20-Jan-26",
            forecastTotalHours: 7,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3730",
            activityId: "A3730",
            name: "Draft Report",
            type: "activity",
            totalHours: 9,
            start: "21-Jan-26",
            finish: "02-Feb-26",
            forecastTotalHours: 9,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3740",
            activityId: "A3740",
            name: "Internal review",
            type: "activity",
            totalHours: 5,
            start: "03-Feb-26",
            finish: "09-Feb-26",
            forecastTotalHours: 5,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3750",
            activityId: "A3750",
            name: "Issue draft to CP",
            type: "activity",
            totalHours: 2,
            start: "10-Feb-26",
            finish: "11-Feb-26",
            forecastTotalHours: 2,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3760",
            activityId: "A3760",
            name: "CP Review",
            type: "activity",
            totalHours: 10,
            start: "12-Feb-26",
            finish: "25-Feb-26",
            forecastTotalHours: 10,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3770",
            activityId: "A3770",
            name: "Presentation to Critical assets",
            type: "activity",
            totalHours: 5,
            start: "26-Feb-26",
            finish: "04-Mar-26",
            forecastTotalHours: 5,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3780",
            activityId: "A3780",
            name: "Update comments from NR and CP",
            type: "activity",
            totalHours: 5,
            start: "05-Mar-26",
            finish: "11-Mar-26",
            forecastTotalHours: 5,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3790",
            activityId: "A3790",
            name: "Final Issue",
            type: "activity",
            totalHours: 2,
            start: "12-Mar-26",
            finish: "13-Mar-26",
            forecastTotalHours: 2,
            status: "Not Started",
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "s12",
    name: "12. NR Boiler Room-Feasibility Study",
    type: "scope",
    totalHours: 86,
    start: "17-Nov-25",
    finish: "16-Mar-26",
    forecastTotalHours: 86,
    status: "",
    engineers: [e("PHa", true), e("MWo")],
    children: [
      {
        id: "a3800",
        activityId: "A3800",
        name: "Review scope, identify elements impacted, develop methodology",
        type: "activity",
        totalHours: 10,
        start: "17-Nov-25",
        finish: "28-Nov-25",
        forecastTotalHours: 10,
        status: "Completed",
        children: [],
      },
      {
        id: "a3810",
        activityId: "A3810",
        name: "Assessment (Gantry crane & Silo foundations, Eversholt Street & Boiler room)",
        type: "activity",
        totalHours: 45,
        start: "01-Dec-25",
        finish: "30-Jan-26",
        forecastTotalHours: 45,
        status: "Completed",
        children: [],
      },
      {
        id: "a3820",
        activityId: "A3820",
        name: "Draft Report",
        type: "activity",
        totalHours: 10,
        start: "02-Feb-26",
        finish: "13-Feb-26",
        forecastTotalHours: 10,
        status: "Completed",
        children: [],
      },
      {
        id: "a3830",
        activityId: "A3830",
        name: "Internal review",
        type: "activity",
        totalHours: 2,
        start: "16-Feb-26",
        finish: "17-Feb-26",
        forecastTotalHours: 2,
        status: "Completed",
        children: [],
      },
      {
        id: "a3840",
        activityId: "A3840",
        name: "Issue draft to CP",
        type: "activity",
        totalHours: 2,
        start: "18-Feb-26",
        finish: "19-Feb-26",
        forecastTotalHours: 2,
        status: "Completed",
        children: [],
      },
      {
        id: "a3850",
        activityId: "A3850",
        name: "Presentation to Stakeholders (MDjv to confirm stakeholders) - TBC",
        type: "activity",
        totalHours: 2,
        start: "20-Feb-26",
        finish: "23-Feb-26",
        forecastTotalHours: 2,
        status: "Not Started",
        children: [],
      },
      {
        id: "a3860",
        activityId: "A3860",
        name: "CP Review",
        type: "activity",
        totalHours: 10,
        start: "20-Feb-26",
        finish: "05-Mar-26",
        forecastTotalHours: 10,
        status: "Not Started",
        children: [],
      },
      {
        id: "a3870",
        activityId: "A3870",
        name: "Update comments from CP and Stakeholders",
        type: "activity",
        totalHours: 5,
        start: "06-Mar-26",
        finish: "12-Mar-26",
        forecastTotalHours: 5,
        status: "Not Started",
        children: [],
      },
      {
        id: "a3880",
        activityId: "A3880",
        name: "Final Issue",
        type: "activity",
        totalHours: 2,
        start: "13-Mar-26",
        finish: "16-Mar-26",
        forecastTotalHours: 2,
        status: "Not Started",
        children: [],
      },
    ],
  },
  {
    id: "s13",
    name: "13. +17mOD and +13 mOD impact assessment excavation",
    type: "scope",
    totalHours: 76,
    start: "21-Jan-26",
    finish: "06-May-26",
    forecastTotalHours: 76,
    status: "",
    engineers: [e("SSi", true), e("ARa"), e("KLa")],
    children: [
      {
        id: "a3890",
        activityId: "A3890",
        name: "Coordination with SDSC (ongoing)",
        type: "activity",
        totalHours: 55,
        start: "21-Jan-26",
        finish: "07-Apr-26",
        forecastTotalHours: 10,
        status: "Not Started",
        children: [],
      },
      {
        id: "t13-1",
        name: "+17mOD",
        type: "task",
        totalHours: 63,
        start: "22-Jan-26",
        finish: "20-Apr-26",
        forecastTotalHours: 63,
        status: "",
        children: [
          {
            id: "a3900",
            activityId: "A3900",
            name: "+17mOD impact assessment (old/new utilities, buildings)",
            type: "activity",
            totalHours: 30,
            start: "22-Jan-26",
            finish: "04-Mar-26",
            forecastTotalHours: 30,
            status: "In Progress",
            children: [],
          },
          {
            id: "a3910",
            activityId: "A3910",
            name: "Draft Report",
            type: "activity",
            totalHours: 10,
            start: "05-Mar-26",
            finish: "18-Mar-26",
            forecastTotalHours: 10,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3920",
            activityId: "A3920",
            name: "Internal review",
            type: "activity",
            totalHours: 2,
            start: "19-Mar-26",
            finish: "20-Mar-26",
            forecastTotalHours: 2,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3930",
            activityId: "A3930",
            name: "Issue draft to CP",
            type: "activity",
            totalHours: 2,
            start: "23-Mar-26",
            finish: "24-Mar-26",
            forecastTotalHours: 2,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3940",
            activityId: "A3940",
            name: "CP Review",
            type: "activity",
            totalHours: 10,
            start: "25-Mar-26",
            finish: "07-Apr-26",
            forecastTotalHours: 10,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3950",
            activityId: "A3950",
            name: "Presentation to Stakeholders",
            type: "activity",
            totalHours: 2,
            start: "08-Apr-26",
            finish: "09-Apr-26",
            forecastTotalHours: 2,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3960",
            activityId: "A3960",
            name: "Update comments from CP and Stakeholders",
            type: "activity",
            totalHours: 5,
            start: "10-Apr-26",
            finish: "16-Apr-26",
            forecastTotalHours: 5,
            status: "Not Started",
            children: [],
          },
          {
            id: "a3970",
            activityId: "A3970",
            name: "Final Issue",
            type: "activity",
            totalHours: 2,
            start: "17-Apr-26",
            finish: "20-Apr-26",
            forecastTotalHours: 2,
            status: "Not Started",
            children: [],
          },
        ],
      },
      {
        id: "t13-2",
        name: "+13mOD",
        type: "task",
        totalHours: 73,
        start: "26-Jan-26",
        finish: "06-May-26",
        forecastTotalHours: 73,
        status: "",
        children: [
          {
            id: "a3980",
            activityId: "A3980",
            name: "+13mOD impact assessment (old/new utilities, buildings/LU)",
            type: "activity",
            totalHours: 50,
            start: "26-Jan-26",
            finish: "03-Apr-26",
            forecastTotalHours: 50,
            status: "In Progress",
            children: [],
          },
          {
            id: "a3990",
            activityId: "A3990",
            name: "Drawings Sketches for Report",
            type: "activity",
            totalHours: 40,
            start: "26-Jan-26",
            finish: "20-Mar-26",
            forecastTotalHours: 40,
            status: "Not Started",
            children: [],
          },
          {
            id: "a4000",
            activityId: "A4000",
            name: "Draft Reports (LU, TW, NR, Buildings)",
            type: "activity",
            totalHours: 10,
            start: "23-Mar-26",
            finish: "03-Apr-26",
            forecastTotalHours: 10,
            status: "Not Started",
            children: [],
          },
          {
            id: "a4010",
            activityId: "A4010",
            name: "Internal review",
            type: "activity",
            totalHours: 2,
            start: "06-Apr-26",
            finish: "07-Apr-26",
            forecastTotalHours: 2,
            status: "Not Started",
            children: [],
          },
          {
            id: "a4020",
            activityId: "A4020",
            name: "Issue draft to CP",
            type: "activity",
            totalHours: 2,
            start: "08-Apr-26",
            finish: "09-Apr-26",
            forecastTotalHours: 2,
            status: "Not Started",
            children: [],
          },
          {
            id: "a4030",
            activityId: "A4030",
            name: "CP Review",
            type: "activity",
            totalHours: 10,
            start: "10-Apr-26",
            finish: "23-Apr-26",
            forecastTotalHours: 10,
            status: "Not Started",
            children: [],
          },
          {
            id: "a4040",
            activityId: "A4040",
            name: "Presentation to Stakeholders",
            type: "activity",
            totalHours: 2,
            start: "24-Apr-26",
            finish: "27-Apr-26",
            forecastTotalHours: 2,
            status: "Not Started",
            children: [],
          },
          {
            id: "a4050",
            activityId: "A4050",
            name: "Update comments from CP and Stakeholders",
            type: "activity",
            totalHours: 5,
            start: "28-Apr-26",
            finish: "04-May-26",
            forecastTotalHours: 5,
            status: "Not Started",
            children: [],
          },
          {
            id: "a4060",
            activityId: "A4060",
            name: "Final Issue",
            type: "activity",
            totalHours: 2,
            start: "05-May-26",
            finish: "06-May-26",
            forecastTotalHours: 2,
            status: "Not Started",
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "s14",
    name: "14. GI GAP Analysis",
    type: "scope",
    totalHours: 51,
    start: "20-Jan-26",
    finish: "31-Mar-26",
    forecastTotalHours: 51,
    status: "",
    engineers: [e("SSi", true), e("TRe")],
    children: [
      {
        id: "a4070",
        activityId: "A4070",
        name: "Review",
        type: "activity",
        totalHours: 51,
        start: "20-Jan-26",
        finish: "31-Mar-26",
        forecastTotalHours: 20,
        status: "In Progress",
        children: [],
      },
      {
        id: "a4080",
        activityId: "A4080",
        name: "CAD Support",
        type: "activity",
        totalHours: 41,
        start: "03-Feb-26",
        finish: "31-Mar-26",
        forecastTotalHours: 41,
        status: "In Progress",
        children: [],
      },
      {
        id: "a4090",
        activityId: "A4090",
        name: "Draft Report",
        type: "activity",
        totalHours: 10,
        start: "17-Feb-26",
        finish: "02-Mar-26",
        forecastTotalHours: 10,
        status: "In Progress",
        children: [],
      },
      {
        id: "a4100",
        activityId: "A4100",
        name: "Internal review",
        type: "activity",
        totalHours: 2,
        start: "03-Mar-26",
        finish: "04-Mar-26",
        forecastTotalHours: 2,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4110",
        activityId: "A4110",
        name: "Issue draft to CP",
        type: "activity",
        totalHours: 2,
        start: "05-Mar-26",
        finish: "06-Mar-26",
        forecastTotalHours: 2,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4120",
        activityId: "A4120",
        name: "CP Review",
        type: "activity",
        totalHours: 10,
        start: "09-Mar-26",
        finish: "20-Mar-26",
        forecastTotalHours: 10,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4130",
        activityId: "A4130",
        name: "Presentation to Stakeholders",
        type: "activity",
        totalHours: 1,
        start: "23-Mar-26",
        finish: "23-Mar-26",
        forecastTotalHours: 1,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4140",
        activityId: "A4140",
        name: "Update comments from CP and Stakeholders",
        type: "activity",
        totalHours: 5,
        start: "24-Mar-26",
        finish: "30-Mar-26",
        forecastTotalHours: 5,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4150",
        activityId: "A4150",
        name: "Final Issue",
        type: "activity",
        totalHours: 1,
        start: "31-Mar-26",
        finish: "31-Mar-26",
        forecastTotalHours: 1,
        status: "Not Started",
        children: [],
      },
    ],
  },
  {
    id: "s15",
    name: "15. LUL Charing Cross",
    type: "scope",
    totalHours: 95,
    start: "02-Feb-26",
    finish: "12-Jun-26",
    forecastTotalHours: null,
    status: "",
    engineers: [e("ANa", true), e("PHa"), e("ANi"), e("DMo"), e("JWr"), e("APe")],
    children: [
      {
        id: "a4170",
        activityId: "A4170",
        name: "Initial assessment",
        type: "activity",
        totalHours: 15,
        start: "02-Feb-26",
        finish: "20-Feb-26",
        forecastTotalHours: null,
        status: "In Progress",
        children: [],
      },
      {
        id: "a4180",
        activityId: "A4180",
        name: "Workshop MDJV/LUL",
        type: "activity",
        totalHours: 8,
        start: "23-Feb-26",
        finish: "04-Mar-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4190",
        activityId: "A4190",
        name: "Detail Assessment",
        type: "activity",
        totalHours: 45,
        start: "25-Feb-26",
        finish: "28-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4200",
        activityId: "A4200",
        name: "Draft Report",
        type: "activity",
        totalHours: 10,
        start: "29-Apr-26",
        finish: "12-May-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4210",
        activityId: "A4210",
        name: "Internal review",
        type: "activity",
        totalHours: 2,
        start: "13-May-26",
        finish: "14-May-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4220",
        activityId: "A4220",
        name: "Issue draft to CP",
        type: "activity",
        totalHours: 2,
        start: "15-May-26",
        finish: "18-May-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4230",
        activityId: "A4230",
        name: "CP Review",
        type: "activity",
        totalHours: 10,
        start: "19-May-26",
        finish: "01-Jun-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4240",
        activityId: "A4240",
        name: "Presentation to Stakeholders",
        type: "activity",
        totalHours: 2,
        start: "02-Jun-26",
        finish: "03-Jun-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4250",
        activityId: "A4250",
        name: "Update comments from CP and Stakeholders",
        type: "activity",
        totalHours: 5,
        start: "04-Jun-26",
        finish: "10-Jun-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4260",
        activityId: "A4260",
        name: "Final Issue",
        type: "activity",
        totalHours: 2,
        start: "11-Jun-26",
        finish: "12-Jun-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
    ],
  },
  {
    id: "s16",
    name: "16. Tunnel GIR",
    type: "scope",
    totalHours: 64,
    start: "02-Feb-26",
    finish: "30-Apr-26",
    forecastTotalHours: null,
    status: "",
    engineers: [e("SSi", true), e("TRe")],
    children: [
      {
        id: "a4270",
        activityId: "A4270",
        name: "Review",
        type: "activity",
        totalHours: 30,
        start: "02-Feb-26",
        finish: "13-Mar-26",
        forecastTotalHours: null,
        status: "In Progress",
        children: [],
      },
      {
        id: "a4280",
        activityId: "A4280",
        name: "Draft Report",
        type: "activity",
        totalHours: 10,
        start: "16-Mar-26",
        finish: "27-Mar-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4290",
        activityId: "A4290",
        name: "Internal review",
        type: "activity",
        totalHours: 2,
        start: "30-Mar-26",
        finish: "31-Mar-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4300",
        activityId: "A4300",
        name: "Issue draft to CP",
        type: "activity",
        totalHours: 2,
        start: "01-Apr-26",
        finish: "02-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4310",
        activityId: "A4310",
        name: "CP Review",
        type: "activity",
        totalHours: 10,
        start: "03-Apr-26",
        finish: "16-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4320",
        activityId: "A4320",
        name: "Presentation to Stakeholders",
        type: "activity",
        totalHours: 2,
        start: "17-Apr-26",
        finish: "20-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4330",
        activityId: "A4330",
        name: "Update comments from CP and Stakeholders",
        type: "activity",
        totalHours: 5,
        start: "21-Apr-26",
        finish: "27-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4340",
        activityId: "A4340",
        name: "Final Issue",
        type: "activity",
        totalHours: 3,
        start: "28-Apr-26",
        finish: "30-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
    ],
  },
  {
    id: "s17",
    name: "17. ECI Euston House & NR _Geobear",
    type: "scope",
    totalHours: 72,
    start: "26-Jan-26",
    finish: "05-May-26",
    forecastTotalHours: null,
    status: "",
    engineers: [e("SFl", true), e("PHa"), e("SSi"), e("ANa")],
    children: [
      {
        id: "a4350",
        activityId: "A4350",
        name: "Workshop 1 NR MDJV (TBC)",
        type: "activity",
        totalHours: 1,
        start: "26-Jan-26",
        finish: "26-Jan-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4360",
        activityId: "A4360",
        name: "Workshop 2 EH MDJV (TBC)",
        type: "activity",
        totalHours: 1,
        start: "26-Jan-26",
        finish: "26-Jan-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4370",
        activityId: "A4370",
        name: "Review scope and deliverables, prepare programme",
        type: "activity",
        totalHours: 10,
        start: "28-Jan-26",
        finish: "10-Feb-26",
        forecastTotalHours: null,
        status: "Completed",
        children: [],
      },
      {
        id: "a4380",
        activityId: "A4380",
        name: "Ongoing coordination with Geobear",
        type: "activity",
        totalHours: 70,
        start: "28-Jan-26",
        finish: "05-May-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4390",
        activityId: "A4390",
        name: "Risk Register",
        type: "activity",
        totalHours: 62,
        start: "30-Jan-26",
        finish: "27-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4400",
        activityId: "A4400",
        name: "Assumption Register",
        type: "activity",
        totalHours: 62,
        start: "09-Feb-26",
        finish: "05-May-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4410",
        activityId: "A4410",
        name: "Kick of meeting - Geobear",
        type: "activity",
        totalHours: 2,
        start: "11-Feb-26",
        finish: "12-Feb-26",
        forecastTotalHours: null,
        status: "Completed",
        children: [],
      },
      {
        id: "a4420",
        activityId: "A4420",
        name: "Draft drawings",
        type: "activity",
        totalHours: 20,
        start: "02-Mar-26",
        finish: "27-Mar-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4430",
        activityId: "A4430",
        name: "Draft Report",
        type: "activity",
        totalHours: 10,
        start: "16-Mar-26",
        finish: "27-Mar-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4440",
        activityId: "A4440",
        name: "Internal review - Report / Drawings",
        type: "activity",
        totalHours: 5,
        start: "30-Mar-26",
        finish: "03-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4450",
        activityId: "A4450",
        name: "Issue draft to CP - Report / Drawings",
        type: "activity",
        totalHours: 2,
        start: "06-Apr-26",
        finish: "07-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4460",
        activityId: "A4460",
        name: "CP Review",
        type: "activity",
        totalHours: 10,
        start: "08-Apr-26",
        finish: "21-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4470",
        activityId: "A4470",
        name: "Update comments",
        type: "activity",
        totalHours: 5,
        start: "22-Apr-26",
        finish: "28-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4480",
        activityId: "A4480",
        name: "Final Issue",
        type: "activity",
        totalHours: 2,
        start: "29-Apr-26",
        finish: "30-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
    ],
  },
  {
    id: "s18",
    name: "18. Euston street GMA updates (impacts to residual buildings)",
    type: "scope",
    totalHours: 51,
    start: "02-Feb-26",
    finish: "13-Apr-26",
    forecastTotalHours: null,
    status: "",
    engineers: [e("SSi", true), e("AMa")],
    children: [
      {
        id: "a4490",
        activityId: "A4490",
        name: "Desk study",
        type: "activity",
        totalHours: 10,
        start: "02-Feb-26",
        finish: "13-Feb-26",
        forecastTotalHours: null,
        status: "Completed",
        children: [],
      },
      {
        id: "a4500",
        activityId: "A4500",
        name: "Assessment",
        type: "activity",
        totalHours: 10,
        start: "16-Feb-26",
        finish: "27-Feb-26",
        forecastTotalHours: null,
        status: "In Progress",
        children: [],
      },
      {
        id: "a4510",
        activityId: "A4510",
        name: "Draft Report",
        type: "activity",
        totalHours: 10,
        start: "02-Mar-26",
        finish: "13-Mar-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4520",
        activityId: "A4520",
        name: "Internal review",
        type: "activity",
        totalHours: 2,
        start: "16-Mar-26",
        finish: "17-Mar-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4530",
        activityId: "A4530",
        name: "Issue draft to CP",
        type: "activity",
        totalHours: 2,
        start: "18-Mar-26",
        finish: "19-Mar-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4540",
        activityId: "A4540",
        name: "CP Review",
        type: "activity",
        totalHours: 10,
        start: "20-Mar-26",
        finish: "02-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4550",
        activityId: "A4550",
        name: "Update comments",
        type: "activity",
        totalHours: 5,
        start: "03-Apr-26",
        finish: "09-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4560",
        activityId: "A4560",
        name: "Final Issue",
        type: "activity",
        totalHours: 2,
        start: "10-Apr-26",
        finish: "13-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "t18-1",
        name: "Settlement Deeds (TBC)",
        type: "task",
        totalHours: 46,
        start: "09-Feb-26",
        finish: "13-Apr-26",
        forecastTotalHours: null,
        status: "",
        children: [
          {
            id: "a4570",
            activityId: "A4570",
            name: "Get: List of buildings",
            type: "activity",
            totalHours: 5,
            start: "09-Feb-26",
            finish: "13-Feb-26",
            forecastTotalHours: null,
            status: "Not Started",
            children: [],
          },
          {
            id: "a4580",
            activityId: "A4580",
            name: "Settlement reports TBC as per NR of reports identified (TBC)",
            type: "activity",
            totalHours: 10,
            start: "16-Feb-26",
            finish: "27-Feb-26",
            forecastTotalHours: null,
            status: "Not Started",
            children: [],
          },
          {
            id: "a4590",
            activityId: "A4590",
            name: "Draft Report (TBC)",
            type: "activity",
            totalHours: 10,
            start: "02-Mar-26",
            finish: "13-Mar-26",
            forecastTotalHours: null,
            status: "Not Started",
            children: [],
          },
          {
            id: "a4600",
            activityId: "A4600",
            name: "Internal review (TBC)",
            type: "activity",
            totalHours: 2,
            start: "16-Mar-26",
            finish: "17-Mar-26",
            forecastTotalHours: null,
            status: "Not Started",
            children: [],
          },
          {
            id: "a4610",
            activityId: "A4610",
            name: "Issue draft to CP (TBC)",
            type: "activity",
            totalHours: 2,
            start: "18-Mar-26",
            finish: "19-Mar-26",
            forecastTotalHours: null,
            status: "Not Started",
            children: [],
          },
          {
            id: "a4620",
            activityId: "A4620",
            name: "CP Review (TBC)",
            type: "activity",
            totalHours: 10,
            start: "20-Mar-26",
            finish: "02-Apr-26",
            forecastTotalHours: null,
            status: "Not Started",
            children: [],
          },
          {
            id: "a4630",
            activityId: "A4630",
            name: "Update comments (TBC)",
            type: "activity",
            totalHours: 5,
            start: "03-Apr-26",
            finish: "09-Apr-26",
            forecastTotalHours: null,
            status: "Not Started",
            children: [],
          },
          {
            id: "a4640",
            activityId: "A4640",
            name: "Final Issue (TBC)",
            type: "activity",
            totalHours: 2,
            start: "10-Apr-26",
            finish: "13-Apr-26",
            forecastTotalHours: null,
            status: "Not Started",
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "s19",
    name: "19. Utilities South Watermain & TAS LU met line",
    type: "scope",
    totalHours: 43,
    start: "09-Feb-26",
    finish: "08-Apr-26",
    forecastTotalHours: null,
    status: "",
    engineers: [e("ANa", true), e("ARa"), e("MWo")],
    children: [
      {
        id: "a4650",
        activityId: "A4650",
        name: "Assesment",
        type: "activity",
        totalHours: 10,
        start: "09-Feb-26",
        finish: "20-Feb-26",
        forecastTotalHours: null,
        status: "Completed",
        children: [],
      },
      {
        id: "a4660",
        activityId: "A4660",
        name: "Draft Report",
        type: "activity",
        totalHours: 10,
        start: "23-Feb-26",
        finish: "06-Mar-26",
        forecastTotalHours: null,
        status: "Completed",
        children: [],
      },
      {
        id: "a4670",
        activityId: "A4670",
        name: "Meeting with LU (TBC)",
        type: "activity",
        totalHours: 5,
        start: "02-Mar-26",
        finish: "06-Mar-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4680",
        activityId: "A4680",
        name: "Internal review",
        type: "activity",
        totalHours: 2,
        start: "09-Mar-26",
        finish: "10-Mar-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4690",
        activityId: "A4690",
        name: "Issue draft to CP",
        type: "activity",
        totalHours: 2,
        start: "11-Mar-26",
        finish: "12-Mar-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4700",
        activityId: "A4700",
        name: "CP Review",
        type: "activity",
        totalHours: 10,
        start: "13-Mar-26",
        finish: "26-Mar-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4710",
        activityId: "A4710",
        name: "Presentation to Stakeholders",
        type: "activity",
        totalHours: 2,
        start: "27-Mar-26",
        finish: "30-Mar-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4720",
        activityId: "A4720",
        name: "Update comments from CP and Stakeholders",
        type: "activity",
        totalHours: 5,
        start: "31-Mar-26",
        finish: "06-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
      {
        id: "a4730",
        activityId: "A4730",
        name: "Final Issue",
        type: "activity",
        totalHours: 2,
        start: "07-Apr-26",
        finish: "08-Apr-26",
        forecastTotalHours: null,
        status: "Not Started",
        children: [],
      },
    ],
  },
];

export function buildProgrammeNodesFromSeed(codeToId: Map<string, string>): ProgrammeNode[] {
  function mapAlloc(a: SeedAlloc): EngineerAllocation {
    const engineerId = codeToId.get(a.code);
    if (!engineerId) {
      throw new Error(`Seed data references unknown engineer code: ${a.code}`);
    }
    return {
      engineerId,
      isLead: a.isLead,
      plannedHrs: a.plannedHrs,
      forecastHrs: a.forecastHrs,
    };
  }

  function mapNode(n: SeedProgrammeNode): ProgrammeNode {
    return {
      ...n,
      engineers: n.engineers?.map(mapAlloc),
      children: n.children.map(mapNode),
    };
  }

  return rollupTotalHoursInTree(seedProgrammeData.map(mapNode));
}
