import type { EngineerAllocation, ProgrammeNode } from "@/components/programme/types";
import type { ProjectUpsertRow } from "@/types/project";
import { applyProgrammeRollups } from "@/lib/programme/applyProgrammeRollups";
import { SEED_LONDON_OFFICE_ID } from "@/lib/programme/seedConfig";
import { SEED_617_PROJECT_ENGINEER_RATE_ROWS } from "@/lib/programme/seedEngineers";
import type { SeedProgrammeNode } from "@/lib/programme/seedProgrammeData";
import { rollupTotalHoursForSeedNodes } from "@/lib/programme/totalHoursRollup";

export const IVER_EGHAM_PROJECT_ID = "2" as const;

export const iverEghamProjectRow: ProjectUpsertRow = {
  id: IVER_EGHAM_PROJECT_ID,
  project_code: "617",
  name: "Iver & Egham",
  client: "Barhale / Network Rail",
  office_id: SEED_LONDON_OFFICE_ID,
  status: "active",
  fixed_fee: 270_000,
  start_date: "2025-07-01",
  end_date: "2026-09-30",
};

/** Engineer rates for 617 — derived from `seedProjectRates2` in seedEngineers. */
export const IVER_EGHAM_PROJECT_ENGINEER_RATES = SEED_617_PROJECT_ENGINEER_RATE_ROWS;

const e = (code: string, isLead = false, plannedHrs: number | null = null) => ({
  code,
  isLead,
  plannedHrs,
});

/**
 * WBS for 617 (Iver & Egham, project code 617).
 * Scopes map to the deliverable groups in the Activity Schedule.
 * Activity hours derived from fee values ÷ blended rate (≈£131/hr).
 * Activity statuses reflect project state as of Apr 2026.
 */
const rawIverEghamNodes: SeedProgrammeNode[] = [
  {
    id: "617-s1",
    name: "Mobilisation",
    type: "scope",
    quotedAmount: 17240.04,
    totalHours: 132,
    start: "01-Jul-25",
    finish: "16-Sep-25",
    status: "",
    engineers: [e("BLy", true, 80), e("AFe", false, 52)],
    children: [
      {
        id: "617-a1",
        activityId: "A0010",
        name: "Mobilisation",
        type: "activity",
        totalHours: 132,
        start: "01-Jul-25",
        finish: "16-Sep-25",
        status: "Completed",
        children: [],
      },
    ],
  },
  {
    id: "617-s2",
    name: "Stage 1 Design - 15no. Trenchless Crossings",
    type: "scope",
    quotedAmount: 47003.53,
    totalHours: 360,
    start: "01-Jul-25",
    finish: "31-Oct-25",
    status: "",
    engineers: [
      e("AFe", true, 180),
      e("SKu", false, 100),
      e("BLy", false, 50),
      e("JWr", false, 480),
    ],
    children: [
      {
        id: "617-a2",
        activityId: "A0020",
        name: "Structural Design of Shaft incl Linings approval by Barhale",
        type: "activity",
        totalHours: 54,
        start: "01-Jul-25",
        finish: "31-Oct-25",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a3",
        activityId: "A0030",
        name: "Geotechnical Design Report Approval by Barhale",
        type: "activity",
        totalHours: 54,
        start: "01-Jul-25",
        finish: "31-Oct-25",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a4",
        activityId: "A0040",
        name: "Design of Pipejacking pipe Approval by Barhale",
        type: "activity",
        totalHours: 36,
        start: "01-Jul-25",
        finish: "31-Oct-25",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a5",
        activityId: "A0050",
        name: "Barhale Approval of Stage 1 Pipejacking design drawings",
        type: "activity",
        totalHours: 108,
        start: "01-Aug-25",
        finish: "31-Oct-25",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a6",
        activityId: "A0060",
        name: "Barhale Approval of Stage 1 Shaft Design Drawings",
        type: "activity",
        totalHours: 108,
        start: "01-Aug-25",
        finish: "31-Oct-25",
        status: "In Progress",
        children: [],
      },
    ],
  },
  {
    id: "617-s3",
    name: "8No. National Highway Crossings / Local Roads Crossings",
    type: "scope",
    quotedAmount: 103260.38,
    totalHours: 789,
    start: "01-Sep-25",
    finish: "09-Sep-26",
    status: "",
    engineers: [
      e("LCh", true, 280),
      e("KLa", false, 240),
      e("JWr", false, 436),
      e("APe", false, 89),
    ],
    children: [
      {
        id: "617-a7",
        activityId: "A0070",
        name: "Ground Movement Assessment Approval by Barhale",
        type: "activity",
        totalHours: 79,
        start: "01-Sep-25",
        finish: "31-Oct-25",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a8",
        activityId: "A0080",
        name: "AIP Drawings Approval by Barhale",
        type: "activity",
        totalHours: 79,
        start: "01-Nov-25",
        finish: "31-Jan-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a9",
        activityId: "A0090",
        name: "Damage Assessment Approval by Barhale",
        type: "activity",
        totalHours: 79,
        start: "01-Nov-25",
        finish: "12-Feb-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a10",
        activityId: "A0100",
        name: "Stage 1 Utilities / Infrastructure competed",
        type: "activity",
        totalHours: 197,
        start: "01-Dec-25",
        finish: "02-Mar-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a11",
        activityId: "A0110",
        name: "Interface Management complete",
        type: "activity",
        totalHours: 79,
        start: "01-Sep-25",
        finish: "16-Jun-26",
        status: "Not Started",
        children: [],
      },
      {
        id: "617-a12",
        activityId: "A0120",
        name: "AIP Submitted",
        type: "activity",
        totalHours: 197,
        start: "01-Sep-25",
        finish: "16-Jun-26",
        status: "Not Started",
        children: [],
      },
      {
        id: "617-a13",
        activityId: "A0130",
        name: "AIP Granted",
        type: "activity",
        totalHours: 79,
        start: "01-Jun-26",
        finish: "09-Sep-26",
        status: "Not Started",
        children: [],
      },
    ],
  },
  {
    id: "617-s4",
    name: "3No. Network Rail Crossings",
    type: "scope",
    quotedAmount: 42936.42,
    totalHours: 329,
    start: "01-Sep-25",
    finish: "20-Jul-26",
    status: "",
    engineers: [e("AFe", true, 150), e("SKu", false, 100), e("BLy", false, 79)],
    children: [
      {
        id: "617-a14",
        activityId: "A0140",
        name: "Ground Movement Assessment Approval by Barhale",
        type: "activity",
        totalHours: 33,
        start: "01-Sep-25",
        finish: "31-Oct-25",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a15",
        activityId: "A0150",
        name: "Drawings Approval by Barhale",
        type: "activity",
        totalHours: 33,
        start: "01-Nov-25",
        finish: "31-Jan-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a16",
        activityId: "A0160",
        name: "Damage Assessment Approval by Barhale",
        type: "activity",
        totalHours: 33,
        start: "01-Nov-25",
        finish: "19-Jan-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a17",
        activityId: "A0170",
        name: "Stage 1 Utilities / Infrastructure competed",
        type: "activity",
        totalHours: 33,
        start: "01-Nov-25",
        finish: "04-Feb-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a18",
        activityId: "A0180",
        name: "Interface Management complete",
        type: "activity",
        totalHours: 82,
        start: "01-Nov-25",
        finish: "24-Apr-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a19",
        activityId: "A0190",
        name: "AIP Submitted",
        type: "activity",
        totalHours: 82,
        start: "01-Nov-25",
        finish: "24-Apr-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a20",
        activityId: "A0200",
        name: "AIP Granted",
        type: "activity",
        totalHours: 33,
        start: "01-Apr-26",
        finish: "20-Jul-26",
        status: "Not Started",
        children: [],
      },
    ],
  },
  {
    id: "617-s5",
    name: "2No. River / Environmental Agency Crossings",
    type: "scope",
    quotedAmount: 29779.8,
    totalHours: 229,
    start: "01-Nov-25",
    finish: "20-Apr-26",
    status: "",
    engineers: [e("LCh", true, 140), e("JWr", false, 433)],
    children: [
      {
        id: "617-a21",
        activityId: "A0210",
        name: "Ground Movement Assessment Approval by Barhale",
        type: "activity",
        totalHours: 23,
        start: "01-Nov-25",
        finish: "31-Jan-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a22",
        activityId: "A0220",
        name: "Drawings Approval by Barhale",
        type: "activity",
        totalHours: 23,
        start: "01-Nov-25",
        finish: "31-Jan-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a23",
        activityId: "A0230",
        name: "Damage Assessment Approval by Barhale",
        type: "activity",
        totalHours: 23,
        start: "01-Nov-25",
        finish: "12-Jan-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a24",
        activityId: "A0240",
        name: "Stage 1 Utilities / Infrastructure competed",
        type: "activity",
        totalHours: 23,
        start: "01-Nov-25",
        finish: "28-Jan-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a25",
        activityId: "A0250",
        name: "Interface Management complete",
        type: "activity",
        totalHours: 57,
        start: "01-Nov-25",
        finish: "09-Feb-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a26",
        activityId: "A0260",
        name: "AIP Submitted",
        type: "activity",
        totalHours: 57,
        start: "01-Nov-25",
        finish: "09-Feb-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a27",
        activityId: "A0270",
        name: "AIP Granted",
        type: "activity",
        totalHours: 23,
        start: "01-Feb-26",
        finish: "20-Apr-26",
        status: "In Progress",
        children: [],
      },
    ],
  },
  {
    id: "617-s6",
    name: "2No. Other Stakeholders Crossings",
    type: "scope",
    quotedAmount: 29779.8,
    totalHours: 229,
    start: "01-Nov-25",
    finish: "12-Jun-26",
    status: "",
    engineers: [e("SKu", true, 140), e("KLa", false, 89)],
    children: [
      {
        id: "617-a28",
        activityId: "A0280",
        name: "Ground Movement Assessment Approval by Barhale",
        type: "activity",
        totalHours: 23,
        start: "01-Nov-25",
        finish: "31-Jan-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a29",
        activityId: "A0290",
        name: "Drawings Approval by Barhale",
        type: "activity",
        totalHours: 23,
        start: "01-Nov-25",
        finish: "31-Jan-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a30",
        activityId: "A0300",
        name: "Damage Assessment Approval by Barhale",
        type: "activity",
        totalHours: 23,
        start: "01-Nov-25",
        finish: "31-Jan-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a31",
        activityId: "A0310",
        name: "Stage 1 Utilities / Infrastructure competed",
        type: "activity",
        totalHours: 23,
        start: "01-Nov-25",
        finish: "31-Jan-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a32",
        activityId: "A0320",
        name: "Interface Management complete",
        type: "activity",
        totalHours: 57,
        start: "01-Nov-25",
        finish: "03-Apr-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a33",
        activityId: "A0330",
        name: "AIP Submitted",
        type: "activity",
        totalHours: 57,
        start: "01-Nov-25",
        finish: "03-Apr-26",
        status: "In Progress",
        children: [],
      },
      {
        id: "617-a34",
        activityId: "A0340",
        name: "AIP Granted",
        type: "activity",
        totalHours: 23,
        start: "01-Mar-26",
        finish: "12-Jun-26",
        status: "Not Started",
        children: [],
      },
    ],
  },
];

/** WBS totals on scope rows are derived from children before any DB export. */
export const iverEghamSeedData: SeedProgrammeNode[] =
  rollupTotalHoursForSeedNodes(rawIverEghamNodes);

export function buildIverEghamProgrammeNodes(codeToId: Map<string, string>): ProgrammeNode[] {
  function mapAlloc(a: {
    code: string;
    isLead: boolean;
    plannedHrs: number | null;
  }): EngineerAllocation {
    const engineerId = codeToId.get(a.code);
    if (!engineerId) throw new Error(`617 WBS references unknown engineer code: ${a.code}`);
    return {
      engineerId,
      isLead: a.isLead,
      plannedHrs: a.plannedHrs,
      weeklyScopeLimitHrs: null,
      rate: "A",
    };
  }

  function mapNode(n: SeedProgrammeNode): ProgrammeNode {
    return {
      ...n,
      engineers: n.engineers?.map(mapAlloc),
      children: n.children.map(mapNode),
    };
  }

  return applyProgrammeRollups(iverEghamSeedData.map(mapNode));
}
